#!/usr/bin/with-contenv sh

# externally mounted volumes are owned by root, but we want to access the database as the mongodb user
chown -R mongodb:mongodb /var/lib/mongodb /var/log/mongodb

mongod --config /etc/mongod.conf
